security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Disable security for certain paths (e.g., CSS, JS, images, profiler)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Main firewall for authenticated users
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:

                - App\Security\UserAuthenticator  # Use this to specify your custom authenticator
            logout:
                path: app_logout
                # Redirection after logout
                target: app_esports_accueil_

    # Access control settings
#    access_control:
#        - { path: ^/profile, roles: ROLE_GAMER }
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/coach, roles: ROLE_COACH }

