security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Disable security for certain paths (e.g., CSS, JS, images, profiler)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Main firewall for authenticated users
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\UserAuthenticator  # Specify custom authenticator

            logout:
                path: app_logout  # Path for logout
                target: app_esports_accueil_  # Redirection after logout

    # Access control settings (uncomment and configure based on roles)
    # access_control:
    #    - { path: ^/profile, roles: ROLE_GAMER }
    #    - { path: ^/admin, roles: ROLE_ADMIN }
    #    - { path: ^/coach, roles: ROLE_COACH }
