# Default security settings
security:
    # Password hashing configuration
    password_hashers:
        App\Entity\User: 'auto' # Automatically select the hashing algorithm for your User entity

    # User provider: Use Doctrine's entity provider for fetching users from the database
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # Assuming email is used as the unique identifier

    # Firewalls: configure the security behavior of different parts of your application
    firewalls:
        # Disable security for development and assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall: This is the main security area for authenticated users
        main:
            # Lazy loading helps to optimize authentication performance
            lazy: true
            # Use the user provider configured above
            provider: app_user_provider
            # Custom authenticator (if you created one)
            custom_authenticator: App\Security\UserAuthenticator
            # Logout configuration: specify logout path and redirect target
            logout:
                path: app_logout
                # Uncomment the next line to redirect after logout (optional)
                # target: app_home

            remember_me:
                secret: '%kernel.secret%' # Use the kernel secret to encrypt the remember-me token
                lifetime: 604800 # Remember me for 7 days
                path: / # Make it available throughout the entire application
                always_remember_me: true

            # CSRF protection for login forms (enabled by default)
            csrf_protection: true

    # Access control: restrict access to certain routes based on roles
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allow anyone to access the login page
        - { path: ^/admin, roles: ROLE_ADMIN } # Only admins can access /admin
        - { path: ^/profile, roles: ROLE_USER } # Only authenticated users can access /profile

# Testing specific configuration (to speed up tests by reducing password hashing workload)
when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4 # Use the lowest possible cost for bcrypt
                time_cost: 3 # Lowest value for argon
                memory_cost: 10 # Lowest value for argon
